name: Build and Deploy
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          
      - name: Build production
        run: |
          npm install -g cssnano-cli terser html-minifier
          mkdir -p dist/images dist/js dist/pages
          cssnano styles/styles.css dist/styles.min.css
          
          # Copier les ressources
          cp JS/combined.min.js dist/js/
          cp images/*.webp dist/images/
          cp images/logo-Photoroom.png dist/images/
          
          # Minifier les fichiers HTML
          html-minifier --collapse-whitespace --remove-comments --remove-optional-tags --remove-redundant-attributes --remove-script-type-attributes --remove-tag-whitespace --use-short-doctype index.html -o dist/index.html
          html-minifier --collapse-whitespace --remove-comments --remove-optional-tags --remove-redundant-attributes --remove-script-type-attributes --remove-tag-whitespace --use-short-doctype pages/contact.html -o dist/pages/contact.html
          
          # Modifier les chemins dans les fichiers HTML
          sed -i 's/..\/styles\/styles.css/.\/styles.min.css/g' dist/index.html
          sed -i 's/\.\/js\/combined.min.js/.\/js\/combined.min.js/g' dist/index.html
          
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: dist